shoots_path: "~/browser_shoots"

scripts:
  google:
    name: "google"
    url: "http://www.google.de"
    commands: |
      open "/"
      window_maximize
      shot before
      type "id=lst-ib", "fernando guillen"
      click "name=btnG", wait_for :page
      pause 3
      shot after


  miniclip:
    name: "miniclip"
    url: "http://www.miniclip.com/games/de/"
    commands: |
      open "/"
      window_maximize
      shot

  brandengage:
    name: "brandengage"
    url: "http://staging.iframe.sponsorpay.com"
    commands: |
      open "/test/brandengage.html"
      window_maximize
      click "link=be_1372_dedicated"
      pause 5
      get_alert
      click "link=sp.showVideo();"
      pause 5
      shot

browsers:
  windows-firefox:
    name: "windows-firefox"
    host: 10.211.55.4
    port: 4444
    browser: "*firefox"

  windows-iexplore:
    name: "windows-iexploreproxy"
    host: 10.211.55.4
    port: 4444
    browser: "*iexploreproxy"

  linux-firefox:
    name: "linux-firefox"
    host: 10.211.55.5
    port: 4444
    browser: "*firefox"