output_path: "~/browser_shoots"
extensions:
  - "./examples/extension0.rb"

tests:
  debug: |
    log "argument1", "argument2"
    try "puts driver.to_s"
    debug
    try "puts 'ending'"

browsers:
  ios-chrome:
    url: "http://127.0.0.1:4444/wd/hub"
    type: "chrome"
    vm: "My VM"

suites:
  suite1:
    tests:
      - debug
    browsers:
      - ios-chrome