output_path: "~/browser_shoots"

tests:
  google: |
    navigate.to "http://www.google.com"
    shot

  miniclip: |
    navigate.to "http://www.miniclip.com/games/de/"
    shot

browsers:
  ios-firefox:
    url: "http://127.0.0.1:4444/wd/hub"
    type: "firefox"

  ios-chrome:
    url: "http://127.0.0.1:4444/wd/hub"
    type: "chrome"

suites:
  suite1:
    tests:
      - google
      - miniclip
    browsers:
      - ios-firefox
      - ios-chrome

  suite2:
    tests:
      - google
    browsers:
      - ios-chrome

