output_path: "~/browser_shoots"

scripts:
  google:
    name: "google"
    url: "http://www.google.de"
    commands: |
      open "/"
      window_maximize
      shot before
      type "id=lst-ib", "fernando guillen"
      click "name=btnG"
      pause 3
      shot after


  miniclip:
    name: "miniclip"
    url: "http://www.miniclip.com/games/de/"
    commands: |
      open "/"
      window_maximize
      shot

browsers:
  windows-firefox:
    name: "windows-firefox"
    host: 10.211.55.4
    port: 4444
    browser: "*firefox"

  windows-iexplore:
    name: "windows-iexploreproxy"
    host: 10.211.55.4
    port: 4444
    browser: "*iexploreproxy"