output_path: "~/browser_shooter"

scripts:
  lightbox:
    name: "lightbox"
    url: "http://localhost:3000"
    commands: |
      open "/test/browser_shooter/lightbox_bareplayer.html"
      window_maximize
      shot


browsers:
  windows-firefox:
    name: "osx-firefox"
    host: 127.0.0.1
    port: 4444
    browser: "*firefox"