output_path: "~/browser_shoots"

scripts:
  google:
    name: "google"
    commands: |
      navigate.to "http://www.google.de"
      shot before
      type "input[name='q']", "beautiful houses"
      click "input[name='btnG']"
      pause 3
      click "a.kls"
      pause 3
      shot after

  miniclip:
    name: "miniclip"
    commands: |
      navigate.to "http://www.miniclip.com/games/de/"
      shot

browsers:
  ios-firefox:
    name: "ios-firefox"
    url: "http://127.0.0.1:4444/wd/hub"
    browser: "firefox"

  ios-chrome:
    name: "ios-chrome"
    url: "http://127.0.0.1:4444/wd/hub"
    browser: "chrome"