shoots_path: "~/browser_shoots"

scripts:
  dedicated_bareplayer:
    name: "dedicated_bareplayer"
    url: "http://192.168.70.149:3000"
    commands: |
      window_maximize
      window_focus
      open "/test/widgets/dedicated_bareplayer.html"
      pause 10
      focus "id=continue_button"
      click "id=play-video-link"
      pause 10
      shot
      shot_system

browsers:
  windows-firefox:
    name: "windows-firefox"
    host: 10.211.55.4
    port: 4444
    browser: "*firefox"

  windows-iexplore:
    name: "windows-iexploreproxy"
    host: 10.211.55.4
    port: 4444
    browser: "*iexploreproxy"