output_path: "~/browser_shooter"

scripts:
  lightbox:
    name: "lightbox"
    url: "http://localhost:3000"
    commands: |
      open "/test/browser_shooter/lightbox_bareplayer.html"
      window_maximize
      pause 5
      alert
      click "link=Show video"
      pause 5
      select_frame "_sp_wiframe"
      run_script "$f().play()"
      wait_for_element "css=span.enabled", :timeout_in_seconds => 15
      click "css=span.enabled"
      pause 5
      alert

browsers:
  windows-firefox:
    name: "osx-firefox"
    host: 127.0.0.1
    port: 4444
    browser: "*firefox"