output_path: "~/browser_shoots"

tests: "./external_tests"

browsers:
  ios-firefox:
    url: "http://127.0.0.1:4444/wd/hub"
    type: "firefox"
    vm: "myVM"

  ios-chrome:
    url: "http://127.0.0.1:4444/wd/hub"
    type: "chrome"
    vm: "myVM"

suites:
  suite1:
    tests:
      - google
      - miniclip
    browsers:
      - ios-firefox
      - ios-chrome