output_path: "~/browser_shooter"

scripts:
  lightbox:
    name: "lightbox"
    url: "http://192.168.70.52:3000"
    commands: |
      open "/test/browser_shooter/lightbox_bareplayer.html"
      window_maximize
      shot_system
      pause 5
      alert
      click "link=Show video"
      pause 5
      shot_system
      select_frame "_sp_wiframe"
      run_script "$f().play()"
      wait_for_element "css=span.enabled", :timeout_in_seconds => 15
      shot_system
      click "css=span.enabled"
      pause 8
      shot_system
      alert
      select_frame "relative=up"
      click "id=sp_close_x"
      alert
      wait_for_condition "selenium.browserbot.getCurrentWindow().document.getElementById('sp_lightbox').style.display == 'none'", 10000
      shot_system


browsers:
  osx-firefox:
    name: "osx-firefox"
    host: 127.0.0.1
    port: 4444
    browser: "*firefox"

  windows-firefox:
    name: "windows-explorer"
    host: 10.211.55.4
    port: 4444
    browser: "*iexploreproxy"